spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/video_online_course
    username: owner
    password: owner
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect